// class ColumnCacheDataTable
//
// Automaticaly generated file
// Generated by: AGRUSERS\bard.hustveit
// Time: 20.04.2007
// Path: D:\dev\src\utils\SqlStudio\SqlExecute\DbSchemaCache

/////////////////////////////////////////////////////////////////
// This file can be manually edited, it will not be overwritten.
/////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;

namespace SqlExecute.DbSchemaCache
{
    public class ColumnCacheDataTable : ColumnCacheDataTableBase
    {
        public ColumnCacheDataTable(DbProviderFactory factory, DbConnection connection)
            : base(factory, connection)
        {
        }

        public ColumnCacheDataTable(DbProviderFactory factory, string connectionString)
            : base(factory, connectionString)
        {
        }

        public ColumnCacheDataTable(DbProviderFactory factory)
            : base(factory)
        {
        }
    }
}