// class ColumnCacheDataRowBase
//
// Automaticaly generated file
// Generated by: AGRUSERS\bard.hustveit
// Time: 20.04.2007
// Path: D:\dev\src\utils\SqlStudio\SqlExecute\DbSchemaCache

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;

namespace SqlExecute.DbSchemaCache
{
    /// <summary>
    /// Typed DataRow for table: column_cache
    /// </summary>
	public class ColumnCacheDataRowBase : DataRow
	{
        /// <summary>
        /// Constructor
        /// This class isn't manually created, use DataTable.NewDbRow()
        /// </summary>
        /// <param name="dataRowBuilder"></param>
		public ColumnCacheDataRowBase(DataRowBuilder dataRowBuilder)
			: base(dataRowBuilder)
		{
		}

        /// <summary>
        /// Get array of primery key columns
        /// </summary>
        /// <returns>string array of primary key columns</returns>
		public static string[] GetPKeys()
		{
			return new string[] { "table_name", "column_name" };
		}

        /// <summary>
        /// Get array of all columns
        /// </summary>
        /// <returns>string array of columns</returns>
		public static string[] GetColumns()
		{
			return new string[] { "table_name", "column_name", "ordinal_position", "data_type", "column_length", "is_nullable", "primary_key" };
		}
		
		
		/// <summary>
        /// Column table_name
        /// </summary>
		public static string table_nameColumn = "table_name";
		
		/// <summary>
        /// Get or Set table_name value
        /// </summary>
		public string table_name
		{
			get { return (string)this[table_nameColumn]; }
			set { this[table_nameColumn] = value; }
		}
		
		/// <summary>
        /// Column column_name
        /// </summary>
		public static string column_nameColumn = "column_name";
		
		/// <summary>
        /// Get or Set column_name value
        /// </summary>
		public string column_name
		{
			get { return (string)this[column_nameColumn]; }
			set { this[column_nameColumn] = value; }
		}
		
		/// <summary>
        /// Column ordinal_position
        /// </summary>
		public static string ordinal_positionColumn = "ordinal_position";
		
		/// <summary>
        /// Get or Set ordinal_position value
        /// </summary>
		public long ordinal_position
		{
			get { return (long)this[ordinal_positionColumn]; }
			set { this[ordinal_positionColumn] = value; }
		}
		
		/// <summary>
        /// Column data_type
        /// </summary>
		public static string data_typeColumn = "data_type";
		
		/// <summary>
        /// Get or Set data_type value
        /// </summary>
		public string data_type
		{
			get 
            {
                if (this[data_typeColumn] == DBNull.Value)
                    return "";
                return (string)this[data_typeColumn]; 
            }
			set { this[data_typeColumn] = value; }
		}

        public static string column_lengthColumn = "column_length";

        /// <summary>
        /// Get or Set data_type value
        /// </summary>
        public int column_length
        {
            get
            {
                return (int)this[column_lengthColumn];
            }
            set { this[column_lengthColumn] = value; }
        }

		/// <summary>
        /// Column is_nullable
        /// </summary>
		public static string is_nullableColumn = "is_nullable";
		
		/// <summary>
        /// Get or Set is_nullable value
        /// </summary>
		public bool is_nullable
		{
			get { return (bool)this[is_nullableColumn]; }
			set { this[is_nullableColumn] = value; }
		}
		
		/// <summary>
        /// Column primary_key
        /// </summary>
		public static string primary_keyColumn = "primary_key";
		
		/// <summary>
        /// Get or Set primary_key value
        /// </summary>
		public bool primary_key
		{
			get { return (bool)this[primary_keyColumn]; }
			set { this[primary_keyColumn] = value; }
		}
		
	}
}